illionillion/tech-museum

docs/api-endpoint.yaml

Closes #22 
APIのエンドポイントとその入出力を定義

APIのエンドポイントを設計

---

@types/articles.d.ts
app/frontend/[[...slug]]/page.tsx
contents/frontend/react/use-state.md
utils/articles.ts
utils/next.ts

ダイナミックルーティングでマークダウンファイルの取得

---

app/api/search/perplexityApi.ts

# Perplexity APIとの通信ロジックを作成

---

.github/workflows/quality.yml
app/frontend/[[...slug]]/page.tsx
components/forms/copy-button.tsx
components/md/code-block.tsx
components/md/custom-markdown.tsx
components/md/linked-heading.tsx
components/md/md-utils.ts
contents/frontend/react/mermaid.md
package.json
pnpm-lock.yaml

マークダウンのカスタマイズ実装

---

app/api/types/responseMessage.ts

Closes # 
APIのレスポンスメッセージを定義したファイルを作成

レスポンスメッセージを定義

---

@types/@clack-prompts.d.ts
contents/frontend/react/mermaid.md
contents/frontend/react/use-state.md
package.json
scripts/contributors.ts
scripts/utils.ts

コントリビューターのスクリプト追加

---

app/api/search/perplexityApi.ts
app/api/search/root.ts
app/api/search/searchService.ts
app/api/types/article.ts

各プラットフォーム（Qiita, Zenn, Hatena）の記事を検索するロジックの作成

---

app/api/config.ts
app/api/search/perplexityApi.ts
app/api/search/root.ts
app/api/search/route.ts
app/api/search/searchService.ts
package.json
pnpm-lock.yaml

Closes # 
backendブランチ内でGithub Actionsが失敗する箇所を修正
- axiosライブラリのインストール
- configファイルを作成

Github Actionsが失敗する箇所を修正

---

app/api/articles/[url]/route.ts
app/api/articles/route.ts

記事情報のCRUD機能を実装

---

@types/articles.d.ts
app/frontend/[[...slug]]/page.tsx
components/data-display/contributors.tsx
components/data-display/scroll-shadow.tsx
components/layouts/article-layout.tsx
components/md/md-utils.ts
components/navigation/next-link.tsx
components/navigation/table-of-contents.tsx
components/typography/index.ts
components/typography/text-with-code.tsx
scripts/contributors.ts

記事表示のページ作成

---

app/api/likes/article/[url]/route.ts
app/api/likes/route.ts
app/api/likes/user/[id]/route.ts

いいねのCRUD機能を実装

---

app/api/bookmarks/article/[url]/route.ts
app/api/bookmarks/route.ts
app/api/bookmarks/user/[id]/route.ts
app/api/likes/route.ts

ブックマークのCRUD機能を実装

---

.github/workflows/sync-main-to-article-stage.yml
.github/workflows/update-search-and-contributors.yml

ci: ワークフローのブランチ変更・同期用作成

---

app/page.tsx

Closes # 
topページのデザイン作成
コンポーネンント作成
コンポーネント間レイアウトの作成
サイズの微調整
コンテンツ部分tabUIの作成
link tabの修正が必要

feat: top デザインレイアウト完成

---

.github/workflows/quality.yml
app/api/articles/[url]/route.ts
app/api/articles/route.ts
app/api/bookmarks/article/[url]/route.ts
app/api/bookmarks/route.ts
app/api/bookmarks/user/[id]/route.ts
app/api/follows/from/[id]/route.ts
app/api/follows/route.ts
app/api/follows/to/[id]/route.ts
app/api/likes/article/[url]/route.ts
app/api/likes/route.ts
app/api/likes/user/[id]/route.ts
docs/api-endpoint.yaml

型を宣言をしてなかった箇所を修正

---

CONTRIBUTING.ja.md
CONTRIBUTING.md
README.md

Closes # 
https://github.com/illionillion/oss-blog/issues/96

Yamada UIの記述を追加&表記を修正

---

app/oss-blog/[[...slug]]/page.tsx
contents/mobile/android/android-wear-os-basic.md

Closes # 
Closes https://github.com/illionillion/oss-blog/issues/103

docs: OSS Blogの説明記事を作成

---

app/api/bookmarks/user/[id]/route.ts
app/api/follows/from/[id]/route.ts
app/api/follows/to/[id]/route.ts
app/api/likes/route.ts
app/api/likes/user/[id]/route.ts
docs/api-endpoint.yaml
prisma/schema.prisma

Closes # 
フロントとの結合の際にUserIdの型が合致しなかったため、APIで扱うUserIdの型を文字列型に修正

UserIdの型をStringに修正

---

i18n/contributors.json
scripts/report-insights.ts

fix: 記事のコントリビューターのみ表示するように修正

---

app/page.tsx
app/welcome/page.tsx

fix: グラデーションの修正

---

components/layouts/footer.tsx

fix: `maxW`指定

---

app/contributors/[username]/page.tsx
contexts/i18n-context.tsx
i18n/contributors.json
scripts/report-insights.ts
utils/next.ts

fix: プロフィールでコントリビューター情報を取得するように変更

---

contents/backend/aspnetcore-basic.md.md

docs: ASP.NET Coreの使い方の記事を追加

---

app/page.tsx
app/welcome/page.tsx
components/navigation/banner.tsx
components/navigation/github-buttons.tsx
components/tutorial/community-introduction.tsx
components/tutorial/feature-card.tsx
components/tutorial/how-to-join.tsx
components/tutorial/question-accordion.tsx

page.tsxに書かれているコンポーネントを移動

---

actions/like-actions.ts

fix: キャッシュしない設定追加

---

actions/like-actions.ts

Reverts illionillion/tech-museum#148

Revert "fix: キャッシュしない設定追加"

---

app/contributors/[username]/page.tsx
components/data-display/article-card.tsx
components/data-display/like-count.tsx
components/disclosure/profile-tabs.tsx
components/disclosure/top-page-tabs.tsx
utils/auth/index.ts

いいね情報をクライアント側でも取得できるように修正

---

.github/workflows/quality.yml
package.json

fix(ci): マイグレートコマンド修正

---

i18n/content.json
scripts/search.ts

メタデータにタグを含めるようにした

---

actions/bookmark-actions.ts
app/backend/[[...slug]]/page.tsx
app/frontend/[[...slug]]/page.tsx
app/git/[[...slug]]/page.tsx
app/infra/[[...slug]]/page.tsx
app/mobile/[[...slug]]/page.tsx
app/tech-museum/[[...slug]]/page.tsx
components/disclosure/profile-tabs.tsx
components/disclosure/top-page-tabs.tsx
components/forms/article-buttons.tsx
components/layouts/article-layout.tsx
prisma/ERD.md
prisma/migrations/20241101162450_add_bookmark/migration.sql
prisma/migrations/20241101164235_make_bookmark_logical_delete/migration.sql
prisma/repositories/bookmark-repository.ts
prisma/schema.prisma
utils/articles.ts
utils/join-articles.ts
utils/next.ts

ブックマーク機能を実装

---

app/contributors/[username]/page.tsx
app/page.tsx
components/disclosure/profile-tabs.tsx
components/disclosure/top-page-tabs.tsx

コントリビュータページのタブ状態をURLに保持するようにした

---

actions/follow-actions.ts
app/contributors/[username]/page.tsx
components/data-display/profile-card.tsx
components/disclosure/top-page-tabs.tsx
components/forms/follow-button.tsx
plop/page/page.tsx.hbs
prisma/ERD.md
prisma/migrations/20241103021057_init/migration.sql
prisma/migrations/20241103024949_init/migration.sql
prisma/repositories/follow-repository.ts
prisma/schema.prisma

フォローフォロワー機能実装

---

app/contributors/[username]/page.tsx
components/disclosure/profile-tabs.tsx

fix: 記事全体とユーザーの記事を切り分けるように修正

---

components/disclosure/profile-tabs.tsx

fix: ユーザー自身の記事が表示されていないので修正

---

components/layouts/header.tsx
components/navigation/user-menu.tsx
utils/auth/index.ts

@taku10101 
- ユーザーのアイコンがはみ出る場合がある
- 遷移先のリンクが間違っていてnot foundになる
これらの問題が見つかったので修正してください。

userメニュー追加"

---

actions/bookmark-actions.ts
actions/follow-actions.ts
actions/like-actions.ts
components/forms/article-buttons.tsx
components/forms/follow-button.tsx

変更操作時にサーバーサイドで認証するようにした

---

.github/workflows/quality.yml

fix: dbコンテナ追加
